routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::group(['middleware' => ['isAdmin'],'prefix' => 'admin', 'as' => 'admin.'], function(){
    Route::resource('courses', \App\Http\Controllers\Admin\CourseController::class);
    Route::delete('courses_perma_del/{id}', [\App\Http\Controllers\Admin\CourseController::class, 'perma_del'])->name('courses.perma_del');
    Route::post('courses_restore/{id}', [\App\Http\Controllers\Admin\CourseController::class, 'restore'])->name('courses.restore');

    Route::resource('lessons', \App\Http\Controllers\Admin\LessonController::class);
    Route::post('lessons_restore/{id}', [\App\Http\Controllers\Admin\LessonController::class,'restore'])->name('lessons.restore');
    Route::delete('lessons_perma_del/{id}', [\App\Http\Controllers\Admin\LessonController::class,'perma_del'])->name('lessons.perma_del');
  
    Route::resource('tests', \App\Http\Controllers\Admin\TestController::class);
    Route::post('tests_restore/{id}', [\App\Http\Controllers\Admin\TestController::class,'restore'])->name('tests.restore');
    Route::delete('tests_perma_del/{id}', [\App\Http\Controllers\Admin\TestController::class,'perma_del'])->name('tests.perma_del');
  
    Route::resource('questions', \App\Http\Controllers\Admin\QuestionController::class);
    Route::post('questions_restore/{id}', [\App\Http\Controllers\Admin\QuestionController::class,'restore'])->name('questions.restore');
    Route::delete('questions_perma_del/{id}', [\App\Http\Controllers\Admin\QuestionController::class,'perma_del'])->name('questions.perma_del');
   
    Route::resource('question_options', \App\Http\Controllers\Admin\QuestionOptionController::class);
    Route::post('question_options_restore/{id}', [\App\Http\Controllers\Admin\QuestionOptionController::class, 'restore'])->name('question_options.restore');
    Route::delete('question_options_perma_del/{id}', [\App\Http\Controllers\Admin\QuestionOptionController::class, 'perma_del'])->name('question_options.perma_del');

    Route::resource('users', \App\Http\Controllers\Admin\UserController::class);
});

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('courses', [App\Http\Controllers\CourseController::class, 'index'])->name('courses.index');
Route::get('courses/{slug}', [App\Http\Controllers\CourseController::class, 'show'])->name('courses.show');
Route::post('courses/payment', [App\Http\Controllers\CourseController::class, 'payment'])->name('courses.payment');
Route::post('course/{course_id}/rating', [App\Http\Controllers\CourseController::class, 'rating'])->name('courses.rating');

Route::get('lessons/{course_id}/{slug}', [App\Http\Controllers\LessonController::class, 'show'])->name('lessons.show');
Route::post('lesson/{slug}/test', [App\Http\Controllers\LessonController::class, 'test'])->name('lessons.test');

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Question extends Model
{
    use HasFactory,SoftDeletes;

    protected $guarded = ['id', 'created_at', 'updated_at'];

    public function options()
    {
        return $this->hasMany(QuestionOption::class);
    }

    public function tests()
    {
        return $this->belongsToMany(Test::class, 'question_test');
    }

}

app/Http/Controllers/Admin/QuestionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Test;
use App\Models\Question;
use Illuminate\Http\Request;
use App\Models\QuestionOption;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Storage;

class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('question_access')) {
            return abort(401);
        }

        if (request('show_deleted') == 1) {
            if (! Gate::allows('question_delete')) {
                return abort(401);
            }
            $questions = Question::onlyTrashed()->get();
        } else {
            $questions = Question::all();
        }

        return view('admin.questions.index', compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('question_create')) {
            return abort(401);
        }
        $tests = Test::get()->pluck('title', 'id');

        return view('admin.questions.create', compact('tests'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (! Gate::allows('question_create')) {
            return abort(401);
        }

        $data = $request->only('question','question_image','score');
        if($request->hasFile('question_image')){
            $data['question_image'] = $request->file('question_image')->store(
                'images/questions', 'public'
            );
        }
        $question = Question::create($data);
        $question->tests()->sync(array_filter((array)$request->input('test')));

        for ($q=1; $q <= 4; $q++) {
            $option = $request->input('option_text_' . $q, '');
            if ($option != '') {
                QuestionOption::create([
                    'question_id' => $question->id,
                    'option_text' => $option,
                    'correct' => $request->input('correct_' . $q) ? 1 : 0,
                ]);
            }
        }

        return redirect()->route('admin.questions.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        if (! Gate::allows('question_edit')) {
            return abort(401);
        }
        $tests = Test::get()->pluck('title', 'id');

        return view('admin.questions.edit', compact('question', 'tests'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Question $question)
    {
        if (! Gate::allows('question_edit')) {
            return abort(401);
        }

        $data = $request->only('question','question_image','score');
        if($request->hasFile('question_image')){
            Storage::disk('public')->delete($question->question_image);
            $data['question_image'] = $request->file('question_image')->store(
                'images/questions', 'public'
            );
        }
        $question->update($data);
        $question->tests()->sync(array_filter((array)$request->input('tests')));



        return redirect()->route('admin.questions.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        if (! Gate::allows('question_delete')) {
            return abort(401);
        }
        $question->delete();

        return redirect()->route('admin.questions.index');
    }

     /**
     * Restore Question from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        if (! Gate::allows('question_delete')) {
            return abort(401);
        }
        $question = Question::onlyTrashed()->findOrFail($id);
        $question->restore();

        return redirect()->route('admin.questions.index');
    }

      /**
     * Permanently delete Question from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function perma_del($id)
    {
        if (! Gate::allows('question_delete')) {
            return abort(401);
        }
        $question = Question::onlyTrashed()->findOrFail($id);
        $question->forceDelete();

        return redirect()->route('admin.questions.index');
    }
}

resources/views/admin/questions/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="card">
    <div class="card-header">
        Create Question
    </div>

    <div class="card-body">
        <form action="{{ route('admin.questions.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group {{ $errors->has('question') ? 'has-error' : '' }}">
                <label for="question">question*</label>
                <textarea id="question" name="question" rows="5" class="form-control" required>
                    {{ old('question', isset($question) ? $question->question : '') }}
                </textarea>
                @if($errors->has('question'))
                    <em class="invalid-feedback">
                        {{ $errors->first('question') }}
                    </em>
                @endif
            </div>
            <div class="form-group {{ $errors->has('question_image') ? 'has-error' : '' }}">
                <label for="question_image">Question Image*</label>
                <input type="file" id="question_image" name="question_image" class="form-control" />
                @if($errors->has('question_image'))
                    <em class="invalid-feedback">
                        {{ $errors->first('question_image') }}
                    </em>
                @endif
            </div>
            <div class="form-group {{ $errors->has('score') ? 'has-error' : '' }}">
                <label for="score">Score*</label>
                <input type="number" id="score" name="score" class="form-control" value="{{ old('score', isset($question) ? $question->score : '') }}" required />
                @if($errors->has('score'))
                    <em class="invalid-feedback">
                        {{ $errors->first('score') }}
                    </em>
                @endif
            </div>
            <div class="form-group {{ $errors->has('test') ? 'has-error' : '' }}">
                <label for="test">Test*</label>
                <select name="test[]" class="form-control" id="test" multiple >
                    @foreach($tests as $id => $test)
                        <option value="{{ $id }}">{{ $test }}</option>
                    @endforeach
                </select>
                @if($errors->has('test'))
                    <em class="invalid-feedback">
                        {{ $errors->first('test') }}
                    </em>
                @endif
            </div>

            @for ($question=1; $question<=4; $question++)
            <div class="card card-footer">
                <div class="card-body">
                    <div class="row">
                        <div class="col-xs-12 col-12 form-group {{ $errors->has('option_text') ? 'has-error' : '' }}">
                            <label for="option_text">Option Text*</label>
                            <textarea id="option_text" name="{{ 'option_text_'. $question }}" rows="5" style="width: 100%;" class="form-control" required>
                                {{ old('question', isset($question) ? "" : null) }}
                            </textarea>
                                @if($errors->has('option_text_'. $question))
                                    <em class="invalid-feedback">
                                        {{ $errors->first('option_text_'. $question) }}
                                    </em>
                                @endif
                            </div>
                        </div>
                    <div class="row">
                        <div class="col-xs-12 form-group">
                        <label for="option_text">Correct*</label>
                        <input type="checkbox" name="{{ 'correct_' . $question }}">
                            <p class="help-block"></p>
                            @if($errors->has('correct_' . $question))
                                <p class="help-block">
                                    {{ $errors->first('correct_' . $question) }}
                                </p>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
            @endfor
           
            <div>
                <button class="btn btn-danger" type="submit" >Save</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/questions/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="card">
    <div class="card-header">
        Edit Question
    </div>

    <div class="card-body">
        <form action="{{ route('admin.questions.update', $question->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('put')
            <div class="form-group {{ $errors->has('question') ? 'has-error' : '' }}">
                <label for="question">question*</label>
                <textarea id="question" name="question" rows="5" class="form-control" required>
                    {{ old('question', isset($question) ? $question->question : '') }}
                </textarea>
                @if($errors->has('question'))
                    <em class="invalid-feedback">
                        {{ $errors->first('question') }}
                    </em>
                @endif
            </div>
            <div class="form-group {{ $errors->has('question_image') ? 'has-error' : '' }}">
                <label for="question_image">Question Image*</label>
                <input type="file" id="question_image" name="question_image" class="form-control" />
                @if($errors->has('question_image'))
                    <em class="invalid-feedback">
                        {{ $errors->first('question_image') }}
                    </em>
                @endif
            </div>
            <div class="form-group {{ $errors->has('score') ? 'has-error' : '' }}">
                <label for="score">Score*</label>
                <input type="number" id="score" name="score" class="form-control" value="{{ old('score', isset($question) ? $question->score : '') }}" required />
                @if($errors->has('score'))
                    <em class="invalid-feedback">
                        {{ $errors->first('score') }}
                    </em>
                @endif
            </div>
            <div class="form-group {{ $errors->has('test') ? 'has-error' : '' }}">
                <label for="test">Test*</label>
                <select name="test[]" class="form-control" id="test" multiple >
                    @foreach($tests as $id => $test)
                        <option {{ in_array($id, $question->tests->pluck('id')->toArray()) ? 'selected' : null }}  value="{{ $id }}">{{ $test }}</option>
                    @endforeach
                </select>
                @if($errors->has('test'))
                    <em class="invalid-feedback">
                        {{ $errors->first('test') }}
                    </em>
                @endif
            </div>           
            <div>
                <button class="btn btn-danger" type="submit" >Save</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/questions/index.blade.php
@extends('layouts.admin')

@section('content')

    <div class="title d-flex justify-content-between">
        <h3 class="page-title">Question</h3>
        @can('question_create')
        <p >
            <a href="{{ route('admin.questions.create') }}" class="btn btn-success">Add New</a>
            
        </p>
        @endcan
   </div>

    <p class="m-0">
        <ul class="d-flex list-unstyled" style="column-gap: 1rem">
            <li><a href="{{ route('admin.questions.index') }}" style="{{ request('show_deleted') == 1 ? '' : 'font-weight: 700' }}">All</a></li> |
            <li><a href="{{ route('admin.questions.index') }}?show_deleted=1" style="{{ request('show_deleted') == 1 ? 'font-weight: 700' : '' }}">Trash</a></li>
        </ul>
    </p>

<div class="card">
    <div class="card-header">
    Question
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover datatable datatable-Location">
                <thead>
                    <tr>
                        <th width="10">
                            #
                        </th>
                        <th>
                            Question
                        </th>
                        <th>
                            Question Image
                        </th>
                        <th>
                            Score
                        </th>
                        <th>
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>

                @forelse($questions as $question)
                    <tr data-entry-id="{{ $question->id }}">
                        <td>
                        </td>
                        <td>
                            {{ $question->question }}
                        </td>
                        <td>
                        @if($question->question_image)<a href="{{ Storage::url($question->question_image) }}" target="_blank"><img src="{{  Storage::url($question->question_image) }}"/></a>@endif
                        </td>
                        <td>
                            {{ $question->score }}
                        </td>
                        <td>
                        @if( request('show_deleted') == 1 )
                        <form action="{{ route('admin.questions.restore', $question->id) }}" method="POST" onsubmit="return confirm('Are you sure ?');" style="display: inline-block;">
                            @csrf
                            <button type="submit" class="btn btn-xs btn-info" >Restore</button>
                        </form>
                        <form action="{{ route('admin.questions.perma_del', $question->id) }}" method="POST" onsubmit="return confirm('Are you sure ?');" style="display: inline-block;">
                            @csrf
                            @method('delete')
                            <button type="submit" class="btn btn-xs btn-danger" >Delete</button>
                        </form>
                        @else
                            <a class="btn btn-xs btn-info" href="{{ route('admin.questions.edit', $question->id) }}">
                                Edit
                            </a>
                            <form action="{{ route('admin.questions.destroy', $question->id) }}" method="POST" onsubmit="return confirm('Are you sure ?');" style="display: inline-block;">
                                @csrf
                                @method('delete')
                                <button type="submit" class="btn btn-xs btn-danger" >Delete</button>
                            </form>
                        @endif
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td class="text-center" colspan="12">Data Not Found!</td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>


    </div>
</div>
@endsection